{% set version = "1.7.6" %}
{% set gomodule = "github.com/rhysd/actionlint" %}

{% set build_outputs = false %}
{% set build_outputs = true %}  # [linux64]

package:
  name: actionlint-split
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 59b49d1cabe927d2f1ba67b15f4cd44e56b30ba28eaf48f9bdd71274bedb8061

build:
  number: 0

requirements:
  build: []
  host: []
  run: []

test:
  commands:
    - echo "tests in subpackages"

outputs:
  - name: actionlint
    build:
      script:
        - call "%RECIPE_DIR%/bld_actionlint.bat"  # [win]
        - bash "$RECIPE_DIR/build_actionlint.sh"  # [unix]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("go-cgo") }}
        - {{ stdlib("c") }}
        - go-licenses
        - posix  # [win]
    test:
      requires:
        - m2-grep  # [win]
      commands:
        - actionlint --version
        - actionlint --help
        - actionlint --version | grep -iE {{ version.replace(".", "\.") }}

  {% if build_outputs %}
  - name: actionlint-with-shellcheck
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("actionlint", max_pin="x.x.x") }}
        - shellcheck
    test:
      requires:
        - m2-grep  # [win]
      commands:
        - actionlint --version
        - actionlint --help
        - actionlint --version | grep -iE {{ version.replace(".", "\.") }}

  - name: actionlint-with-pyflakes
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("actionlint", max_pin="x.x.x") }}
        - pyflakes
    test:
      requires:
        - m2-grep  # [win]
      commands:
        - actionlint --version
        - actionlint --help
        - actionlint --version | grep -iE {{ version.replace(".", "\.") }}

  - name: actionlint-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("actionlint", max_pin="x.x.x") }}
        - {{ pin_subpackage("actionlint-with-pyflakes", max_pin="x.x.x") }}
        - {{ pin_subpackage("actionlint-with-shellcheck", max_pin="x.x.x") }}
    test:
      requires:
        - m2-grep  # [win]
      commands:
        - actionlint --version
        - actionlint --help
        - actionlint --version | grep -iE {{ version.replace(".", "\.") }}
  {% endif %}

about:
  home: https://{{ gomodule }}
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE.txt
    - license-files/
  summary: Static checker for GitHub Actions workflow files
  doc_url: https://rhysd.github.io/actionlint

extra:
  feedstock-name: actionlint
  recipe-maintainers:
    - bollwyvl
